version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test_task_1
    ports:
      - 5432:5432
